### ISSUE TITLE
Monthly study annotations failed 5/2/23

### ISSUE THREAD

**Issue by cconrad8** [nf-osi/jobs#61]
:x: monthly - monitor_study_annotations failed!

2023-05-02T05:01:53.003-04:00
Error in py_dict_get_item(x, name) : KeyError: 'firstName'
I think this was the error but not sure how to fix it

**Comment by anngvu** [comment]
@cconrad8 We actually fixed this in https://github.com/nf-osi/jobs/pull/55. So somehow I thought I had updated the reference in Service Catalog but didn't. Here are the versions of images for this job: https://github.com/nf-osi/jobs/pkgs/container/jobs-monitor-annotations. So I was supposed to update the image name from `c7c2145` to `605c3c6`. I did somehow update the Confluence page, and then probably got distracted and then later went back and thought that because Confluence was updated, SC was updated. Since no emails were sent out, this was just updated and re-triggered manually.

Anyway, here are probably two ways to avoid this, for myself and future maintainers:
- Maybe use `latest` in Service Catalog so don't have to update Service Catalog as an extra step. 
- Update Service Catalog first, _then_ update Confluence.
