### ISSUE TITLE
Investigate annotation reminder email error

### ISSUE THREAD

**Issue by cconrad8** [nf-osi/jobs#80]
https://www.synapse.org/#!Synapse:syn52619462

Josh received an email for annotation reminders but we have already completed the annotations.  
My first thought - Is this due to the synapse storage manifest not having assay? (syn53059428)

Dear Joshua Roberts,

This is a friendly reminder to please annotate files that you have uploaded to this project in Synapse. They can be annotated using the [Data Curator App](https://sagebio.shinyapps.io/NF_data_curator). The files which need annotation are listed in the folders below:

📁[ Phase A - Clinical Trial Data](https://www.synapse.org/#!Synapse:syn52619462)

NF-OSI encourages (and many NF funders mandate) that data files be annotated so that they and future data users can understand the data. At minimum please provide “resourceType”, “dataType”, “specimenID” and “assay” to help make the data findable. You can find annotation instructions [here](https://help.nf.synapse.org/NFdocs/how-to-annotate-data). If you need help with annotation, please reach out to us at [nf-osi@sagebionetworks.org](mailto:nf-osi@sagebionetworks.org).

Thank you,
NF-OSI Service

**Comment by anngvu** [comment]
Concluding probably not an error on our part. Some annotations used uppercase Assay key, and we look for lowercase. This is very likely because of a short period where schematic uppercased everything when submitting. I will fix these.
<img width="223" alt="image" src="https://github.com/nf-osi/jobs/assets/32753274/501fb0a3-a9b2-4f55-a608-fc0444134d03">
